### ISSUE TITLE
A short proposal

### ISSUE THREAD

**Issue by zyguan** [zwh8800/xware#1]
Thanks for the image. I believe the following `docker-compose.yml` can make things easier ;-)

``` yaml
xware:
  image: zwh8800/xware
  restart: always
  volumes:
    - ./cfg:/xware/cfg
    - ./data:/data
```
